name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  java-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Run Maven tests
        run: cd "Final Project/Workshop 3/java-backend/auth" && mvn -B -ntp clean test
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-test-reports
          path: 'Final Project/Workshop 3/java-backend/auth/target/surefire-reports/**'

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install dependencies
        run: cd "Final Project/Workshop 3/front-end" && npm ci
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || true
      - name: Run Angular tests
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: cd "Final Project/Workshop 3/front-end" && npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: 'Final Project/Workshop 3/front-end/coverage'

  python-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: Final Project/Workshop 3/python-backend/requirements.txt
      - name: Install dependencies
        run: cd "Final Project/Workshop 3/python-backend" && pip install -r requirements.txt
      - name: Smoke import
        run: cd "Final Project/Workshop 3/python-backend" && python -c "import app.main; print('ok')"

  docker-build:
    runs-on: ubuntu-latest
    needs: [java-tests, frontend-tests, python-smoke]
    steps:
      - uses: actions/checkout@v4
      - name: Change to Workshop directory
        run: cd "Final Project/Workshop 3" && pwd && ls -la
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build auth-backend image
        uses: docker/build-push-action@v5
        with:
          context: Final Project/Workshop 3/java-backend/auth
          push: false
          tags: auth-backend:ci
      - name: Build python-backend image
        uses: docker/build-push-action@v5
        with:
          context: Final Project/Workshop 3/python-backend
          push: false
          tags: python-backend:ci
      - name: Build angular-frontend image
        uses: docker/build-push-action@v5
        with:
          context: Final Project/Workshop 3/front-end
          push: false
          tags: angular-frontend:ci
